version: "3.8"
networks:
  _:
    name: "$network"
  private:
    driver: "bridge"
services:
  keycloak:
    image: "jboss/keycloak:15.0.2"
    restart: "unless-stopped"
    environment:
      KEYCLOAK_FRONTEND_URL: "https://${host}/auth"
      PROXY_ADDRESS_FORWARDING: "true"
      # KEYCLOAK_DEFAULT_THEME: "${kcDefaultTheme}"
      DB_VENDOR: "postgres"
      DB_ADDR: "postgres"
      DB_PORT: 5432
      DB_DATABASE: "keycloak"
      DB_USER: "${pgUser}"
      DB_PASSWORD: "${pgPass}"
      KEYCLOAK_USER: "${kcUser}"
      KEYCLOAK_PASSWORD: "${kcPass}"
    volumes:
      - "keycloak:/opt/jboss/keycloak/"
    depends_on:
      - "postgres"
    networks:
      _: {}
      private: {}
  postgres:
    image: "postgres:14-alpine"
    restart: "unless-stopped"
    environment:
      POSTGRES_USER: "${pgUser}"
      POSTGRES_PASSWORD: "${pgPass}"
      POSTGRES_DB: "keycloak"
    volumes:
      - "db:/var/lib/postgresql/data"
    networks:
      private: {}
volumes:
  keycloak: {}
  db: {}
